#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : NaviaRent
email      : naviarent@gmail.com #this is also the email contact forms will go to
description: "La location de paddle en libre-service"
author     : NaviaRent
logo:     #optional, defaults to site title
  path: assets/logo/logo_1.png
  height: 52

collections:
  portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme

# use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mleowdzl"