header:
    title: NaviaRent
    text: La location de paddle en libre-service
    button: En savoir plus
    buttonlink: "#services" # "#{section}" or "URL/page link"

services:
    title: "Services"
    text: "Envie de louer un paddle en tout simplicité ?"
    section: services
    list:
      - title: "Application"
        desc: "Telecharger l'application NaviaRent pour louer un paddle rapidement !"
        icon: fas fa-mobile-alt #find more at https://fontawesome.com/icons
      - title: "Borne connecté"
        desc: "Pas de smartphone ? Prêts de nos casiers retrouvé nos borne connecté pour commencer la location !"
        icon: fas fa-solar-panel
      - title: "Location"
        desc: "Trouvé nos bornes prêts de vos points d'eau préférer !"
        icon: fas fa-search-location

portfolio:
    title: "Portfolio"
    text: "Lorem ipsum dolor sit amet consectetur."
    section: portfolio

about:
    title: "A propos"
    text: "Quelques mots sur nous"
    section: about
    events:
      - title: "Nos débuts"
        year: "2020"
        desc: "Crée au seins de l'école Epitech dans le cadre du projet Epitech Innovation Project, NaviaRent est lancé !"
        image: assets/img/timeline/presentation1.jpg
        alt:
        align: left
#      - title: "An Agency is Born"
#        year: "March 2011"
#        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
#        image: assets/img/timeline/2.jpg
#        alt:
#        align: right
    end: "Faites partie<br>de notre aventure!"

#clients:
#    section: clients
#    max-height: 100px
#    horizontal-scrolling: "" #"yes/no"
#    list:
#      - title: "envato"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/envato.jpg
#      - title: "designmodo"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/designmodo.jpg
#      - title: "themeforest"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/themeforest.jpg
#      - title: "Creative Market"
#        url: https://github.com/raviriley/agency-jekyll-theme
#        logo: assets/img/clients/creative-market.jpg
    
team:
    title: "Notre équipe"
    text: "Lorem ipsum dolor sit amet consectetur."
    section: team
    people:
      - name: "Phil Loctaux"
        role: "Lead Developer"
        image: assets/img/team/phil.jpg
        social:
          - url: https://twitter.com/philippeloctaux
            icon: fab fa-twitter
          - url: https://linkedin.com/in/philippeloctaux
            icon: fab fa-linkedin-in
      - name: "Alexandre Wagner"
        role: "Lead Developer"
        image: assets/img/team/wagner.jpg
        social:
          - url : https://github.com/wagnerwave
            icon: fab fa-github
      - name: "Pierre Barillec"
        role: "Lead Developer"
        image: assets/img/team/pierre.jpg
        social:
          - url: https://github.com/pbarillec
            icon: fab fa-github
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Peter Bessone"
        role: "Lead Developer"
        image: assets/img/team/peter.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "François Lelay"
        role: "Lead Developer"
        image: assets/img/team/papie.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Charles Séry"
        role: "Lead Developer"
        image: assets/img/team/charles.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Baptiste Mottin"
        role: "Lead Developer"
        image: assets/img/team/mottin.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Rémi Balbous"
        role: "Lead Developer"
        image: assets/img/team/remi.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Victor Simon"
        role: "Lead Developer"
        image: assets/img/team/vico.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-twitter
          - url: https://facebook.com
            icon: fab fa-facebook-f
          - url: https://linkedin.com
            icon: fab fa-linkedin-in

contact:
    title: "Contactez-nous!"
    text: ""
    section: contact
    
footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com/naviarent
        icon: "fab fa-twitter"
      - url: https://facebook.com/naviarent
        icon: "fab fa-facebook-f"
      - url: https://www.linkedin.com/company/naviarent
        icon: "fab fa-linkedin-in"
      - url: https://github.com/naviarent
        icon: "fab fa-github"
      - url: https://instagram.com/_naviarent
        icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
